version: '3.8'
services:
  tbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt-4-0125-preview
    volumes:
      - data:/app/usage_logs
    env_file:
      - .env.prod.gpt4
    restart: always
    networks:
      - lan

networks:
  lan:
    name: gpt4-network

volumes:
  data:
    name: gpt4-data